AWSTemplateFormatVersion: 2010-09-09
Description: MykittenApachheServer

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: firstkey 
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      SecurityGroupIds: 
        - first-security-group
      UserData: !Base64 |
        #!/bin/bash 
        yum update -y
        yum install httpd -y
        systemctl start httpd
        systemctl enable httpd
        chmod -R 777 /var/www/html
        cd /var/www/html
        wget https://raw.githubusercontent.com/mustafaslan-devops/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/index.html
        wget https://raw.githubusercontent.com/mustafaslan-devops/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
        wget https://raw.githubusercontent.com/mustafaslan-devops/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
        wget https://raw.githubusercontent.com/mustafaslan-devops/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
        wget https://raw.githubusercontent.com/mustafaslan-devops/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.png
    
  
