AWSTemplateFormatVersion: 2010-09-09
Description: |
  hdhdkencjckfndhvkflfnf
  fmfhfkfnfhgklrbrıeşw.x vhfkf
  lfjvlfönvfşfnvoçdeğsv.


Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache web Server and SSH for secure connection.
      VpcId:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs: